### ISSUE TITLE
not working in java 9

### ISSUE THREAD

**Issue by kinsleykajiva** [Jerady/fontawesomefx-glyphsbrowser#4]
The browser is not opening after I install the newly released version of Java 9.

**Comment by goxr3plus** [comment]
@kinsleykajiva  Needs to be updated for Java 9 . Have you checked the errors you get ? Try to download the .zip folder and run it with command prompt . Open Command Prompt and take the .bat file drop it inside the command Prompt and it will show you the errors . 

It will be some reflection errors for sure . Not tested it yet though :)

**Comment by goxr3plus** [comment]
Link address from ReadMe.md -> http://jensd.de/apps/fontawesomefx-glyphsbrowser/fontawesomefx-glyphsbrowser-1.3.0.zip

**Comment by goxr3plus** [comment]
Here is the Branch for Java 9  Support -> https://github.com/Jerady/fontawesomefx-glyphsbrowser/tree/fontawesomefx-glyphsbrowser-9.0.0

**Comment by goxr3plus** [comment]
@kinsleykajiva  I have just added SearchBar feature give it a try :) 

https://github.com/Jerady/fontawesomefx-glyphsbrowser/pull/5

**Comment by kinsleykajiva** [comment]
ok , i will try it out , thanks .

**Comment by kinsleykajiva** [comment]
I have just tried running it but i am getting this error 
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:945)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
        at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:48)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.lambda$init$0(GlyphsBrowserAppModel.java:92)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.init(GlyphsBrowserAppModel.java:93)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.<init>(GlyphsBrowserAppModel.java:85)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserApp.start(GlyphsBrowserApp.java:41)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:189)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.parser.CSSParser
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 21 more
Exception running application de.jensd.fx.glyphs.browser.GlyphsBrowserApp

**Comment by jjjimenez100** [comment]
The same goes for me.

**Comment by piusalfred** [comment]
I am having the same error the browser does not run on java 9

**Comment by tymur-berezhnoi** [comment]
The same issue for me

**Comment by shubham-sharma-12** [comment]
Not Working for Java 10.

I got the following results after dragging "fontawesomefx-glyphsbrowser" file into cmd.



Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
        at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:48)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.lambda$init$0(GlyphsBrowserAppModel.java:92)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.init(GlyphsBrowserAppModel.java:93)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserAppModel.<init>(GlyphsBrowserAppModel.java:85)
        at de.jensd.fx.glyphs.browser.GlyphsBrowserApp.start(GlyphsBrowserApp.java:41)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.parser.CSSParser
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 21 more
Exception running application de.jensd.fx.glyphs.browser.GlyphsBrowserApp

**Comment by goxr3plus** [comment]
Dear all , it doesn't work because it needs modifications , the libraries are from Java 8 and also the code need to be rewritten a little bit .

When i have time i will publish an updated version . Check also Iconli Font Icons Tutorial  -> https://www.youtube.com/watch?v=o5UewXgUiYY

**Comment by XaviMontero** [comment]
Not Working for Java 11. 
Exception in Application start method
java.lang.reflect.InvocationTargetException

**Comment by raoufOnGithub** [comment]
not working for JDK 14 with OpenJFX 14

**Comment by justAnArthur** [comment]
now working for Java 16... we crying...

**Comment by LuchoNoPrograma** [comment]
not working for Java 17 u.u

**Comment by Youssef-SAIB** [comment]
Not working for jdk21 , help please !
